### ISSUE TITLE
Enhance Search Parameters

### ISSUE THREAD

**Issue by thunsaker** [thunsaker/soup#67]
Allow greater distances, other options.

**Comment by thunsaker** [comment]
While fixing this, look into allowing the search view to display copy/cut properly, right now the uiOptions=Split... is keeping the options below the keyboard. I need to make the menu items for duplicate/original into a "floating" button bar instead of an OptionsMenu.
Discovered in #96

**Comment by thunsaker** [comment]
- [ ] Distance Slider
- [ ] Search location w/o query #32 
- [ ] Search by category #44 
- [ ] Search by Emoji...
- [ ] Convert Duplicate Search Menu into floating view
- [ ] Bring copy/paste back up to the top (Discovered during #97)

**Comment by thunsaker** [comment]
Use the following for theming search view: https://github.com/thunsaker/brevos/blob/master/app/src/main/res/layout/search_layout_actionview.xml
